
import './globals.css'
import { Playfair, Roboto } from 'next/font/google'


const playfair = Playfair({ subsets: ['latin'], weight: ['300', "400", "600", "800"] })

export const roboto = Roboto({ subsets: ['latin'], weight: ["100", "300", "400", "500", "700", "900"] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        {children}

      </body>
    </html>
  )
}
